networks:
  golfmike_network:
    name: golfmike_network
    driver: bridge

services:
  # Celery worker service to process background tasks
  celery_worker:
    platform: linux/arm64  # Specify the platform for compatibility
    container_name: veggie-1
    build:
      context: /Users/gmisner/Documents/GolfMike  # Build context for Dockerfile
      dockerfile: .devcontainer/Dockerfile  # Path to Dockerfile
      args:
        VARIANT: "3.10"  # Python version to use in the container
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  # Broker URL for Celery to connect to Redis
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Backend URL for storing task results
      - PYTHONPATH=/workspace  # Add workspace to PYTHONPATH for module resolution
      - PATH=/home/vscode/.local/bin:$PATH  # Add local bin to PATH
    working_dir: /workspace  # Set working directory inside the container
    volumes:
      - /Users/gmisner/Documents/GolfMike:/workspace  # Mount local directory to container workspace
    command: /bin/bash -c "cd /workspace && celery -A celery_app worker -Q solace,message_processing --loglevel=debug"  # Increased log level to DEBUG
    user: "vscode"  # Run the container as user "vscode"
    depends_on:
      - redis  # Ensure Redis starts before Celery worker
      - postgres  # Ensure Postgres starts before Celery worker
    networks:
      - golfmike_network

  # Add another Celery Worker
  celery_worker_2:
    platform: linux/arm64
    container_name: veggie-2
    build:
      context: /Users/gmisner/Documents/GolfMike
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.10"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/workspace
      - PATH=/home/vscode/.local/bin:$PATH
    working_dir: /workspace
    volumes:
      - /Users/gmisner/Documents/GolfMike:/workspace
    command: /bin/bash -c "cd /workspace && celery -A celery_app worker -Q solace,message_processing --loglevel=debug"
    user: "vscode"
    depends_on:
      - redis
      - postgres
    networks:
      - golfmike_network

  # Add another Celery Worker
  celery_worker_3:
    platform: linux/arm64
    container_name: veggie-3
    build:
      context: /Users/gmisner/Documents/GolfMike
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.10"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/workspace
      - PATH=/home/vscode/.local/bin:$PATH
    working_dir: /workspace
    volumes:
      - /Users/gmisner/Documents/GolfMike:/workspace
    command: /bin/bash -c "cd /workspace && celery -A celery_app worker -Q solace,message_processing --loglevel=debug"
    user: "vscode"
    depends_on:
      - redis
      - postgres
    networks:
      - golfmike_network
  
  # Add another Celery Worker
  celery_worker_4:
    platform: linux/arm64
    container_name: veggie-4
    build:
      context: /Users/gmisner/Documents/GolfMike
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.10"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/workspace
      - PATH=/home/vscode/.local/bin:$PATH
    working_dir: /workspace
    volumes:
      - /Users/gmisner/Documents/GolfMike:/workspace
    command: /bin/bash -c "cd /workspace && celery -A celery_app worker -Q solace,message_processing --loglevel=debug"
    user: "vscode"
    depends_on:
      - redis
      - postgres
    networks:
      - golfmike_network

  # Flower service for monitoring Celery tasks
  flower:
    image: mher/flower:latest
    container_name: flower-pot
    platform: linux/arm64  # Specify the platform for compatibility
    command: ["/bin/sh", "-c", "celery --broker=redis://redis:6379/0 flower --debug"]  # Use /bin/sh to ensure command runs properly
    ports:
      - "5555:5555"  # Expose Flower's web UI on port 5555
    depends_on:
      - redis  # Ensure Redis starts before Flower
      - celery_worker  # Ensure Celery worker starts before Flower
    networks:
      - golfmike_network

  # Redis service for message brokering
  redis:
    container_name: redis
    image: redis:alpine  # Use a lightweight Redis image
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    networks:
      - golfmike_network

  # Postgres service for database storage
  postgres:
    platform: linux/arm64
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /Users/gmisner/Documents/GolfMike/initdb:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - golfmike_network

  # Database initialization service
  db_init:
    platform: linux/amd64  # Specify the platform for compatibility
    build:
      context: /Users/gmisner/Documents/GolfMike  # Build context for Dockerfile
      dockerfile: .devcontainer/Dockerfile  # Path to Dockerfile
      args:
        VARIANT: "3.10"  # Python version to use in the container
    environment:
      - PYTHONPATH=/workspace  # Add workspace to PYTHONPATH for module resolution
      - PATH=/home/vscode/.local/bin:$PATH  # Add local bin to PATH
    working_dir: /workspace  # Set working directory inside the container
    volumes:
      - /Users/gmisner/Documents/GolfMike:/workspace  # Mount local directory to container workspace
    command: /bin/bash -c "cd /workspace && python -c 'from db_config import init_db; init_db()'"  # Command to initialize the database
    user: "vscode"  # Run the container as user "vscode"
    depends_on:
      postgres:
        condition: service_healthy  # Wait for Postgres to be healthy before running
    networks:
      - golfmike_network
  
  # Custom container named "bigtitties" for running a specific Python script
  bigtitties:
    platform: linux/amd64  # Specify the platform for compatibility
    build:
      context: /Users/gmisner/Documents/GolfMike  # Build context for Dockerfile
      dockerfile: .devcontainer/Dockerfile  # Path to Dockerfile
      args:
        VARIANT: "3.10"  # Python version to use in the container
    environment:
      - PYTHONPATH=/workspace  # Add workspace to PYTHONPATH for module resolution
      - PATH=/home/vscode/.local/bin:$PATH  # Add local bin to PATH
    working_dir: /workspace  # Set working directory inside the container
    volumes:
      - /Users/gmisner/Documents/GolfMike:/workspace  # Mount local directory to container workspace
    user: "vscode"  # Run the container as user "vscode"
    depends_on:
      - redis  # Ensure Redis starts before this container
      - postgres  # Ensure Postgres starts before this container
    networks:
      - golfmike_network

volumes:
  postgres_data:
